import Nav from "@/components/Nav/";
import "./globals.css";
import { Raleway } from "next/font/google";
import Footer from "@/components/Footer/";
import Main from "@/components/Main/Main";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-sofia" });

export const metadata = {
  title: "Lentera Inovasi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={raleway.variable}>
        <Nav />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
